spring.application.name=sound-diary
server.port=8080

# Oracle 21c (XE PDB) 표준 설정 (필수)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=sejong
spring.datasource.password=kosa1004

# HikariCP 커넥션 풀 옵션
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.pool-name=SoundDiaryHikariPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL

# 로깅 레벨
logging.level.com.zaxxer.hikari=INFO

#openweather
spring.config.import=optional:classpath:application-secret.properties
openweather.base-url=https://api.openweathermap.org/data/2.5/weather


mybatis.mapper-locations=classpath:mapper/*.xml
#resultType 경로명 선언해놓음
mybatis.type-aliases-package=com.sj.sound_diary.dto
#mybatis컬럼명 java필드명 자동매핑
mybatis.configuration.map-underscore-to-camel-case=true

#서버 세션 타임 설정 1시간
server.servlet.session.timeout=1h